name: Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    strategy:
      matrix:
        go-version: ['1.18', stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go version
      - name: Test
        run: go test ./...
